# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --no-color

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MAKE_HELP_MAKEFILES := $(MAKE_HELP_DIR)Makefile

.PHONY: help
## Displays help for available targets.
help: $(MAKE_HELP_DIR)help.mk
	@echo "Usage: make [<target>...] [<ENV_VAR>=<value>...]"
	@echo ""
	@echo "Targets:"
	@echo ""
	@echo "Cleanup:"
	@echo "  - clean c: Removes all generated files."
	@echo "  - clean-all: Deep clean including caches."
	@echo ""
	@echo "Code Quality:"
	@echo "  - fmt: Formats all Go code."
	@echo "  - lint: Runs all linters."
	@echo "    Vars: LINT_CONFIG Linter config file (default: .golangci.yml)"
	@echo "  - sec security: Checks for security vulnerabilities."
	@echo ""
	@echo "Core:"
	@echo "  - build b: Builds the application with version information embedded."
	@echo "    Vars: VERSION Version string (auto-detected from git tag), COMMIT Git commit hash (auto-detected), BUILD_DATE Build timestamp (auto-generated)"
	@echo "  - install i: Installs the application to your GOPATH."
	@echo "  - test t: Runs the complete test suite with race detection."
	@echo "    Vars: TEST_FLAGS Additional go test flags, INTEGRATION Set to 1 to run integration tests, VERBOSE Set to 1 for verbose test output"
	@echo ""
	@echo "Development:"
	@echo "  - dev dev, run, serve: Starts the development server with hot reload."
	@echo "    Vars: PORT Server port (default: 8080), LOG_LEVEL Log verbosity (debug, info, warn, error)"
	@echo "  - repl: Opens a REPL for interactive development."
	@echo ""
	@echo "Docker:"
	@echo "  - docker-build: Builds the Docker image."
	@echo "    Vars: DOCKER_REGISTRY Docker registry URL, DOCKER_IMAGE Image name (default: myapp), DOCKER_TAG Image tag (default: $$(VERSION))"
	@echo "  - docker-push: Pushes the Docker image to the registry."
	@echo "    Vars: DOCKER_REGISTRY Registry to push to"
	@echo "  - docker-up docker-run: Runs the application in a Docker container."
	@echo "    Vars: DOCKER_PORT Host port to bind (default: 8080)"
	@echo ""
	@echo "Release:"
	@echo "  - release: Creates a new release."
	@echo "    Vars: RELEASE_DIR Directory for release artifacts (default: dist)"
	@echo "  - release-publish: Publishes release to GitHub."
	@echo "    Vars: GITHUB_TOKEN GitHub API token for releases"

.PHONY: help-clean
help-clean: $(MAKE_HELP_DIR)help.mk
	@echo "Target: clean"
	@echo "Aliases: c"
	@echo ""
	@echo "Documentation:"
	@echo "  Removes all generated files."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:132"

.PHONY: help-clean-all
help-clean-all: $(MAKE_HELP_DIR)help.mk
	@echo "Target: clean-all"
	@echo ""
	@echo "Documentation:"
	@echo "  Deep clean including caches."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:137"

.PHONY: help-fmt
help-fmt: $(MAKE_HELP_DIR)help.mk
	@echo "Target: fmt"
	@echo ""
	@echo "Documentation:"
	@echo "  Formats all Go code."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:120"

.PHONY: help-lint
help-lint: $(MAKE_HELP_DIR)help.mk
	@echo "Target: lint"
	@echo "Variables:"
	@echo "  - LINT_CONFIG Linter config file (default: .golangci.yml)"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs all linters."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:115"

.PHONY: help-sec
help-sec: $(MAKE_HELP_DIR)help.mk
	@echo "Target: sec"
	@echo "Aliases: security"
	@echo ""
	@echo "Documentation:"
	@echo "  Checks for security vulnerabilities."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:126"

.PHONY: help-build
help-build: $(MAKE_HELP_DIR)help.mk
	@echo "Target: build"
	@echo "Aliases: b"
	@echo "Variables:"
	@echo "  - VERSION Version string (auto-detected from git tag)"
	@echo "  - COMMIT Git commit hash (auto-detected)"
	@echo "  - BUILD_DATE Build timestamp (auto-generated)"
	@echo ""
	@echo "Documentation:"
	@echo "  Builds the application with version information embedded."
	@echo "  "
	@echo "  The build process:"
	@echo "  1. Generates version info from git"
	@echo "  2. Compiles with ldflags for version embedding"
	@echo "  3. Outputs to bin/ directory"
	@echo "  "
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:28"

.PHONY: help-install
help-install: $(MAKE_HELP_DIR)help.mk
	@echo "Target: install"
	@echo "Aliases: i"
	@echo ""
	@echo "Documentation:"
	@echo "  Installs the application to your GOPATH."
	@echo "  NOTE: Still in \"Core\" category"
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:48"

.PHONY: help-test
help-test: $(MAKE_HELP_DIR)help.mk
	@echo "Target: test"
	@echo "Aliases: t"
	@echo "Variables:"
	@echo "  - TEST_FLAGS Additional go test flags"
	@echo "  - INTEGRATION Set to 1 to run integration tests"
	@echo "  - VERBOSE Set to 1 for verbose test output"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs the complete test suite with race detection."
	@echo "  "
	@echo "  Includes unit tests, integration tests, and race condition detection."
	@echo "  Set INTEGRATION=1 to include integration tests."
	@echo "  "
	@echo "  NOTE: Inherits \"Core\" category from above"
	@echo "  "
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:42"

.PHONY: help-dev
help-dev: $(MAKE_HELP_DIR)help.mk
	@echo "Target: dev"
	@echo "Aliases: dev, run, serve"
	@echo "Variables:"
	@echo "  - PORT Server port (default: 8080)"
	@echo "  - LOG_LEVEL Log verbosity (debug, info, warn, error)"
	@echo ""
	@echo "Documentation:"
	@echo "  Starts the development server with hot reload."
	@echo "  "
	@echo "  Uses air for automatic rebuilds when files change."
	@echo "  Install air: go install github.com/cosmtrek/air@latest"
	@echo "  "
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:104"

.PHONY: help-repl
help-repl: $(MAKE_HELP_DIR)help.mk
	@echo "Target: repl"
	@echo ""
	@echo "Documentation:"
	@echo "  Opens a REPL for interactive development."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:109"

.PHONY: help-docker-build
help-docker-build: $(MAKE_HELP_DIR)help.mk
	@echo "Target: docker-build"
	@echo "Variables:"
	@echo "  - DOCKER_REGISTRY Docker registry URL"
	@echo "  - DOCKER_IMAGE Image name (default: myapp)"
	@echo "  - DOCKER_TAG Image tag (default: $$(VERSION))"
	@echo ""
	@echo "Documentation:"
	@echo "  Builds the Docker image."
	@echo "  "
	@echo "  Creates a multi-stage build for minimal image size."
	@echo "  The image is tagged with both the version and 'latest'."
	@echo "  "
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:60"

.PHONY: help-docker-push
help-docker-push: $(MAKE_HELP_DIR)help.mk
	@echo "Target: docker-push"
	@echo "Variables:"
	@echo "  - DOCKER_REGISTRY Registry to push to"
	@echo ""
	@echo "Documentation:"
	@echo "  Pushes the Docker image to the registry."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:66"

.PHONY: help-docker-up
help-docker-up: $(MAKE_HELP_DIR)help.mk
	@echo "Target: docker-up"
	@echo "Aliases: docker-run"
	@echo "Variables:"
	@echo "  - DOCKER_PORT Host port to bind (default: 8080)"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs the application in a Docker container."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:73"

.PHONY: help-release
help-release: $(MAKE_HELP_DIR)help.mk
	@echo "Target: release"
	@echo "Variables:"
	@echo "  - RELEASE_DIR Directory for release artifacts (default: dist)"
	@echo ""
	@echo "Documentation:"
	@echo "  Creates a new release."
	@echo "  "
	@echo "  This target:"
	@echo "  1. Runs all tests"
	@echo "  2. Builds for all platforms"
	@echo "  3. Creates release archives"
	@echo "  4. Generates checksums"
	@echo "  "
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:86"

.PHONY: help-release-publish
help-release-publish: $(MAKE_HELP_DIR)help.mk
	@echo "Target: release-publish"
	@echo "Variables:"
	@echo "  - GITHUB_TOKEN GitHub API token for releases"
	@echo ""
	@echo "Documentation:"
	@echo "  Publishes release to GitHub."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:92"

# Auto-regenerate help when source Makefiles change
$(MAKE_HELP_DIR)help.mk: $(MAKE_HELP_MAKEFILES)
	@make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 npx make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 echo "make-help not found; install with 'go install github.com/sdlcforge/make-help/cmd/make-help@latest' or 'npm install -g make-help'"
