# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --no-color

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MAKE_HELP_MAKEFILES := $(MAKE_HELP_DIR)Makefile $(MAKE_HELP_DIR)help.mk

## !category Help
.PHONY: help
## Displays help for available targets.
help:
	@for f in $(MAKE_HELP_MAKEFILES); do \
	  if [ "$$f" -nt "$(MAKE_HELP_DIR)help.mk" ]; then \
	    printf 'Warning: %s is newer than help.mk. Run make update-help to refresh.\n' "$$f"; \
	  fi; \
	done
	@printf '%b\n' "Usage: make [<target>...] [<ENV_VAR>=<value>...]"
	@printf '%b\n' ""
	@printf '%b\n' "Targets:"
	@printf '%b\n' ""
	@printf '%b\n' "Cleanup:"
	@printf '%b\n' "  - clean c: Removes all generated files."
	@printf '%b\n' "  - clean-all: Deep clean including caches."
	@printf '%b\n' ""
	@printf '%b\n' "Code Quality:"
	@printf '%b\n' "  - fmt: Formats all Go code."
	@printf '%b\n' "  - lint: Runs all linters."
	@printf '%b\n' "    Vars: LINT_CONFIG Linter config file (default: .golangci.yml)"
	@printf '%b\n' "  - sec security: Checks for security vulnerabilities."
	@printf '%b\n' ""
	@printf '%b\n' "Core:"
	@printf '%b\n' "  - build b: Builds the application with version information embedded."
	@printf '%b\n' "    Vars: VERSION Version string (auto-detected from git tag), COMMIT Git commit hash (auto-detected), BUILD_DATE Build timestamp (auto-generated)"
	@printf '%b\n' "  - install i: Installs the application to your GOPATH."
	@printf '%b\n' "  - test t: Runs the complete test suite with race detection."
	@printf '%b\n' "    Vars: TEST_FLAGS Additional go test flags, INTEGRATION Set to 1 to run integration tests, VERBOSE Set to 1 for verbose test output"
	@printf '%b\n' ""
	@printf '%b\n' "Development:"
	@printf '%b\n' "  - dev dev, run, serve: Starts the development server with hot reload."
	@printf '%b\n' "    Vars: PORT Server port (default: 8080), LOG_LEVEL Log verbosity (debug, info, warn, error)"
	@printf '%b\n' "  - repl: Opens a REPL for interactive development."
	@printf '%b\n' ""
	@printf '%b\n' "Docker:"
	@printf '%b\n' "  - docker-build: Builds the Docker image."
	@printf '%b\n' "    Vars: DOCKER_REGISTRY Docker registry URL, DOCKER_IMAGE Image name (default: myapp), DOCKER_TAG Image tag (default: $$(VERSION))"
	@printf '%b\n' "  - docker-push: Pushes the Docker image to the registry."
	@printf '%b\n' "    Vars: DOCKER_REGISTRY Registry to push to"
	@printf '%b\n' "  - docker-up docker-run: Runs the application in a Docker container."
	@printf '%b\n' "    Vars: DOCKER_PORT Host port to bind (default: 8080)"
	@printf '%b\n' ""
	@printf '%b\n' "Help:"
	@printf '%b\n' "  - help: Displays help for available targets."
	@printf '%b\n' "  - update-help: Regenerates help.mk from source Makefiles."
	@printf '%b\n' ""
	@printf '%b\n' "Release:"
	@printf '%b\n' "  - release: Creates a new release."
	@printf '%b\n' "    Vars: RELEASE_DIR Directory for release artifacts (default: dist)"
	@printf '%b\n' "  - release-publish: Publishes release to GitHub."
	@printf '%b\n' "    Vars: GITHUB_TOKEN GitHub API token for releases"

.PHONY: help-clean
help-clean:
	@printf '%b\n' "Target: clean"
	@printf '%b\n' "Aliases: c"
	@printf '%b\n' ""
	@printf '%b\n' "Removes all generated files."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:132"

.PHONY: help-clean-all
help-clean-all:
	@printf '%b\n' "Target: clean-all"
	@printf '%b\n' ""
	@printf '%b\n' "Deep clean including caches."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:137"

.PHONY: help-fmt
help-fmt:
	@printf '%b\n' "Target: fmt"
	@printf '%b\n' ""
	@printf '%b\n' "Formats all Go code."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:120"

.PHONY: help-lint
help-lint:
	@printf '%b\n' "Target: lint"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - LINT_CONFIG Linter config file (default: .golangci.yml)"
	@printf '%b\n' ""
	@printf '%b\n' "Runs all linters."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:115"

.PHONY: help-sec
help-sec:
	@printf '%b\n' "Target: sec"
	@printf '%b\n' "Aliases: security"
	@printf '%b\n' ""
	@printf '%b\n' "Checks for security vulnerabilities."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:126"

.PHONY: help-build
help-build:
	@printf '%b\n' "Target: build"
	@printf '%b\n' "Aliases: b"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - VERSION Version string (auto-detected from git tag)"
	@printf '%b\n' "  - COMMIT Git commit hash (auto-detected)"
	@printf '%b\n' "  - BUILD_DATE Build timestamp (auto-generated)"
	@printf '%b\n' ""
	@printf '%b\n' "Builds the application with version information embedded."
	@printf '%b\n' ""
	@printf '%b\n' "The build process:"
	@printf '%b\n' "1. Generates version info from git"
	@printf '%b\n' "2. Compiles with ldflags for version embedding"
	@printf '%b\n' "3. Outputs to bin/ directory"
	@printf '%b\n' ""
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:28"

.PHONY: help-install
help-install:
	@printf '%b\n' "Target: install"
	@printf '%b\n' "Aliases: i"
	@printf '%b\n' ""
	@printf '%b\n' "Installs the application to your GOPATH."
	@printf '%b\n' "NOTE: Still in \"Core\" category"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:48"

.PHONY: help-test
help-test:
	@printf '%b\n' "Target: test"
	@printf '%b\n' "Aliases: t"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - TEST_FLAGS Additional go test flags"
	@printf '%b\n' "  - INTEGRATION Set to 1 to run integration tests"
	@printf '%b\n' "  - VERBOSE Set to 1 for verbose test output"
	@printf '%b\n' ""
	@printf '%b\n' "Runs the complete test suite with race detection."
	@printf '%b\n' ""
	@printf '%b\n' "Includes unit tests, integration tests, and race condition detection."
	@printf '%b\n' "Set INTEGRATION=1 to include integration tests."
	@printf '%b\n' ""
	@printf '%b\n' "NOTE: Inherits \"Core\" category from above"
	@printf '%b\n' ""
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:42"

.PHONY: help-dev
help-dev:
	@printf '%b\n' "Target: dev"
	@printf '%b\n' "Aliases: dev, run, serve"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - PORT Server port (default: 8080)"
	@printf '%b\n' "  - LOG_LEVEL Log verbosity (debug, info, warn, error)"
	@printf '%b\n' ""
	@printf '%b\n' "Starts the development server with hot reload."
	@printf '%b\n' ""
	@printf '%b\n' "Uses air for automatic rebuilds when files change."
	@printf '%b\n' "Install air: go install github.com/cosmtrek/air@latest"
	@printf '%b\n' ""
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:104"

.PHONY: help-repl
help-repl:
	@printf '%b\n' "Target: repl"
	@printf '%b\n' ""
	@printf '%b\n' "Opens a REPL for interactive development."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:109"

.PHONY: help-docker-build
help-docker-build:
	@printf '%b\n' "Target: docker-build"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - DOCKER_REGISTRY Docker registry URL"
	@printf '%b\n' "  - DOCKER_IMAGE Image name (default: myapp)"
	@printf '%b\n' "  - DOCKER_TAG Image tag (default: $$(VERSION))"
	@printf '%b\n' ""
	@printf '%b\n' "Builds the Docker image."
	@printf '%b\n' ""
	@printf '%b\n' "Creates a multi-stage build for minimal image size."
	@printf '%b\n' "The image is tagged with both the version and 'latest'."
	@printf '%b\n' ""
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:60"

.PHONY: help-docker-push
help-docker-push:
	@printf '%b\n' "Target: docker-push"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - DOCKER_REGISTRY Registry to push to"
	@printf '%b\n' ""
	@printf '%b\n' "Pushes the Docker image to the registry."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:66"

.PHONY: help-docker-up
help-docker-up:
	@printf '%b\n' "Target: docker-up"
	@printf '%b\n' "Aliases: docker-run"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - DOCKER_PORT Host port to bind (default: 8080)"
	@printf '%b\n' ""
	@printf '%b\n' "Runs the application in a Docker container."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:73"

.PHONY: help-help
help-help:
	@printf '%b\n' "Target: help"
	@printf '%b\n' ""
	@printf '%b\n' "Displays help for available targets."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/help.mk:10"

.PHONY: help-update-help
help-update-help:
	@printf '%b\n' "Target: update-help"
	@printf '%b\n' ""
	@printf '%b\n' "Regenerates help.mk from source Makefiles."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/help.mk:260"

.PHONY: help-release
help-release:
	@printf '%b\n' "Target: release"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - RELEASE_DIR Directory for release artifacts (default: dist)"
	@printf '%b\n' ""
	@printf '%b\n' "Creates a new release."
	@printf '%b\n' ""
	@printf '%b\n' "This target:"
	@printf '%b\n' "1. Runs all tests"
	@printf '%b\n' "2. Builds for all platforms"
	@printf '%b\n' "3. Creates release archives"
	@printf '%b\n' "4. Generates checksums"
	@printf '%b\n' ""
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:86"

.PHONY: help-release-publish
help-release-publish:
	@printf '%b\n' "Target: release-publish"
	@printf '%b\n' "Variables:"
	@printf '%b\n' "  - GITHUB_TOKEN GitHub API token for releases"
	@printf '%b\n' ""
	@printf '%b\n' "Publishes release to GitHub."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/examples/full-featured/Makefile:92"

# Explicit target to regenerate help.mk
## !category Help
.PHONY: update-help
## Regenerates help.mk from source Makefiles.
update-help:
	@make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 npx make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 echo "make-help not found; install with 'go install github.com/sdlcforge/make-help/cmd/make-help@latest' or 'npm install -g make-help'"
