# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --create-help-target

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
GOBIN ?= $(MAKE_HELP_DIR).bin
MAKE_HELP_BIN := $(GOBIN)/make-help
MAKE_HELP_OPTS := --makefile-path $(MAKE_HELP_DIR)Makefile
MAKE_HELP_CMD := $(MAKE_HELP_BIN) $(MAKE_HELP_OPTS)

$(MAKE_HELP_BIN):
	GOBIN=$(abspath $(GOBIN)) go install github.com/sdlcforge/make-help/cmd/make-help@latest

.PHONY: help
# Displays help summary.
help: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD)

.PHONY: help-test
help-test: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target test

.PHONY: help-build
help-build: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target build

.PHONY: help-install
help-install: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target install

.PHONY: help-docker-up
help-docker-up: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target docker-up

.PHONY: help-docker-build
help-docker-build: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target docker-build

.PHONY: help-docker-push
help-docker-push: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target docker-push

.PHONY: help-release
help-release: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target release

.PHONY: help-release-publish
help-release-publish: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target release-publish

.PHONY: help-repl
help-repl: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target repl

.PHONY: help-dev
help-dev: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target dev

.PHONY: help-lint
help-lint: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target lint

.PHONY: help-fmt
help-fmt: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target fmt

.PHONY: help-sec
help-sec: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target sec

.PHONY: help-clean
help-clean: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target clean

.PHONY: help-clean-all
help-clean-all: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target clean-all
