# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --no-color

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MAKE_HELP_MAKEFILES := $(MAKE_HELP_DIR)Makefile

.PHONY: help
## Displays help for available targets.
help: $(MAKE_HELP_DIR)help.mk
	@echo "Usage: make [<target>...] [<ENV_VAR>=<value>...]"
	@echo ""
	@echo "Targets:"
	@echo "  - build: Builds the application binary."
	@echo "    Vars: BUILD_FLAGS Additional flags to pass to the compiler, OUTPUT_DIR Output directory for the binary (default: ./bin)"
	@echo "  - clean: Removes build artifacts and temporary files."
	@echo "  - install: Installs the application to GOPATH/bin."
	@echo "  - serve run, dev: Runs the application in development mode."
	@echo "    Vars: PORT Port to listen on (default: 8080)"
	@echo "  - test: Runs the test suite."
	@echo "    Vars: TEST_FLAGS Additional flags for go test, COVERAGE Enable coverage reporting (set to 1)"

.PHONY: help-build
help-build: $(MAKE_HELP_DIR)help.mk
	@echo "Target: build"
	@echo "Variables:"
	@echo "  - BUILD_FLAGS Additional flags to pass to the compiler"
	@echo "  - OUTPUT_DIR Output directory for the binary (default: ./bin)"
	@echo ""
	@echo "Documentation:"
	@echo "  Builds the application binary."
	@echo "  Creates an optimized build in the ./bin directory."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/uncategorized-targets/Makefile:11"

.PHONY: help-clean
help-clean: $(MAKE_HELP_DIR)help.mk
	@echo "Target: clean"
	@echo ""
	@echo "Documentation:"
	@echo "  Removes build artifacts and temporary files."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/uncategorized-targets/Makefile:22"

.PHONY: help-install
help-install: $(MAKE_HELP_DIR)help.mk
	@echo "Target: install"
	@echo ""
	@echo "Documentation:"
	@echo "  Installs the application to GOPATH/bin."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/uncategorized-targets/Makefile:26"

.PHONY: help-serve
help-serve: $(MAKE_HELP_DIR)help.mk
	@echo "Target: serve"
	@echo "Aliases: run, dev"
	@echo "Variables:"
	@echo "  - PORT Port to listen on (default: 8080)"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs the application in development mode."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/uncategorized-targets/Makefile:32"

.PHONY: help-test
help-test: $(MAKE_HELP_DIR)help.mk
	@echo "Target: test"
	@echo "Variables:"
	@echo "  - TEST_FLAGS Additional flags for go test"
	@echo "  - COVERAGE Enable coverage reporting (set to 1)"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs the test suite."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/uncategorized-targets/Makefile:18"

# Auto-regenerate help when source Makefiles change
$(MAKE_HELP_DIR)help.mk: $(MAKE_HELP_MAKEFILES)
	@make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 npx make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 echo "make-help not found; install with 'go install github.com/sdlcforge/make-help/cmd/make-help@latest' or 'npm install -g make-help'"
