# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --create-help-target

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
GOBIN ?= $(MAKE_HELP_DIR).bin
MAKE_HELP_BIN := $(GOBIN)/make-help
MAKE_HELP_OPTS := --makefile-path $(MAKE_HELP_DIR)Makefile
MAKE_HELP_CMD := $(MAKE_HELP_BIN) $(MAKE_HELP_OPTS)

$(MAKE_HELP_BIN):
	GOBIN=$(abspath $(GOBIN)) go install github.com/sdlcforge/make-help/cmd/make-help@latest

.PHONY: help
# Displays help summary.
help: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD)

.PHONY: help-build
help-build: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target build

.PHONY: help-test
help-test: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target test

.PHONY: help-clean
help-clean: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target clean

.PHONY: help-install
help-install: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target install

.PHONY: help-serve
help-serve: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target serve
