version: 2
project_name: make-help

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/make-help
    binary: make-help
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sdlcforge/make-help/internal/version.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: sdlcforge
    name: make-help
  draft: false
  prerelease: auto

brews:
  - name: make-help
    repository:
      owner: sdlcforge
      name: homebrew-tap
    homepage: https://github.com/sdlcforge/make-help
    description: Generate static help files for Makefiles from specially-formatted comments
    license: MIT
    install: |
      bin.install "make-help"
    test: |
      system "#{bin}/make-help", "--version"
