# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MAKE_HELP_MAKEFILES := $(MAKE_HELP_DIR)Makefile $(MAKE_HELP_DIR)help.mk

## !category Help
.PHONY: help
## Displays help for available targets.
help:
	@for f in $(MAKE_HELP_MAKEFILES); do \
	  if [ "$$f" -nt "$(MAKE_HELP_DIR)help.mk" ]; then \
	    printf '\033[0;33mWarning: %s is newer than help.mk. Run make update-help to refresh.\033[0m\n' "$$f"; \
	  fi; \
	done
	@printf '%b\n' "Usage: make [<target>...] [<ENV_VAR>=<value>...]"
	@printf '%b\n' ""
	@printf '%b\n' "Targets:"
	@printf '%b\n' ""
	@printf '%b\n' "\033[1;36mBuild:\033[0m"
	@printf '%b\n' "  - \033[1;32mbuild\033[0m: \033[0;37mBuilds the make-help binary.\033[0m"
	@printf '%b\n' "  - \033[1;32mclean\033[0m: \033[0;37mDeletes all built artifacts.\033[0m"
	@printf '%b\n' ""
	@printf '%b\n' "\033[1;36mHelp:\033[0m"
	@printf '%b\n' "  - \033[1;32mhelp\033[0m: \033[0;37mDisplays help for available targets.\033[0m"
	@printf '%b\n' "  - \033[1;32mupdate-help\033[0m: \033[0;37mRegenerates help.mk from source Makefiles.\033[0m"
	@printf '%b\n' ""
	@printf '%b\n' "\033[1;36mQuality:\033[0m"
	@printf '%b\n' "  - \033[1;32mlint\033[0m: \033[0;37mRun golangci-lint\033[0m"
	@printf '%b\n' "  - \033[1;32mlint-fix\033[0m: \033[0;37mRun golangci-lint with auto-fix\033[0m"
	@printf '%b\n' "  - \033[1;32mqa\033[0m: \033[0;37mRun all quality checks (test.all + lint).\033[0m"
	@printf '%b\n' ""
	@printf '%b\n' "\033[1;36mTest:\033[0m"
	@printf '%b\n' "  - \033[1;32mtest\033[0m \033[0;33mt\033[0m: \033[0;37mRun unit tests.\033[0m"
	@printf '%b\n' "  - \033[1;32mtest.all\033[0m: \033[0;37mRun all tests (unit + integration).\033[0m"
	@printf '%b\n' "  - \033[1;32mtest.integration\033[0m: \033[0;37mRun integration tests.\033[0m"
	@printf '%b\n' "  - \033[1;32mtest.unit\033[0m: \033[0;37mRun unit tests.\033[0m"

.PHONY: help-build
help-build:
	@printf '%b\n' "\033[1;32mTarget: build\033[0m"
	@printf '%b\n' ""
	@printf '%b\n' "Builds the make-help binary."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:10"

.PHONY: help-clean
help-clean:
	@printf '%b\n' "\033[1;32mTarget: clean\033[0m"
	@printf '%b\n' "Deletes all built artifacts."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:17"

.PHONY: help-help
help-help:
	@printf '%b\n' "\033[1;32mTarget: help\033[0m"
	@printf '%b\n' "Displays help for available targets."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/help.mk:10"

.PHONY: help-update-help
help-update-help:
	@printf '%b\n' "\033[1;32mTarget: update-help\033[0m"
	@printf '%b\n' "Regenerates help.mk from source Makefiles."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/help.mk:136"

.PHONY: help-lint
help-lint:
	@printf '%b\n' "\033[1;32mTarget: lint\033[0m"
	@printf '%b\n' ""
	@printf '%b\n' "Run golangci-lint"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:49"

.PHONY: help-lint-fix
help-lint-fix:
	@printf '%b\n' "\033[1;32mTarget: lint-fix\033[0m"
	@printf '%b\n' "Run golangci-lint with auto-fix"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:54"

.PHONY: help-qa
help-qa:
	@printf '%b\n' "\033[1;32mTarget: qa\033[0m"
	@printf '%b\n' "Run all quality checks (test.all + lint)."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:59"

.PHONY: help-test
help-test:
	@printf '%b\n' "\033[1;32mTarget: test\033[0m"
	@printf '%b\n' "\033[0;33mAliases: t\033[0m"
	@printf '%b\n' ""
	@printf '%b\n' "Run unit tests."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:31"

.PHONY: help-test.all
help-test.all:
	@printf '%b\n' "\033[1;32mTarget: test.all\033[0m"
	@printf '%b\n' "Run all tests (unit + integration)."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:43"

.PHONY: help-test.integration
help-test.integration:
	@printf '%b\n' "\033[1;32mTarget: test.integration\033[0m"
	@printf '%b\n' "Run integration tests. Use 'test.all' to run all tests."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:38"

.PHONY: help-test.unit
help-test.unit:
	@printf '%b\n' "\033[1;32mTarget: test.unit\033[0m"
	@printf '%b\n' ""
	@printf '%b\n' "Run unit tests. Use 'test.all' to run all tests."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:24"

# Explicit target to regenerate help.mk
## !category Help
.PHONY: update-help
## Regenerates help.mk from source Makefiles.
update-help:
	@make-help --makefile-path $(MAKE_HELP_DIR)Makefile || \
	 npx make-help --makefile-path $(MAKE_HELP_DIR)Makefile || \
	 echo "make-help not found; install with 'go install github.com/sdlcforge/make-help/cmd/make-help@latest' or 'npm install -g make-help'"
