# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --no-color

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MAKE_HELP_MAKEFILES := $(MAKE_HELP_DIR)Makefile

.PHONY: help
## Displays help for available targets.
help: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Usage: make [<target>...] [<ENV_VAR>=<value>...]"
	@printf '%b\n' ""
	@printf '%b\n' "Targets:"
	@printf '%b\n' ""
	@printf '%b\n' "Build:"
	@printf '%b\n' "  - build: Builds the make-help binary."
	@printf '%b\n' "  - clean: Deletes all built artifacts."
	@printf '%b\n' ""
	@printf '%b\n' "Quality:"
	@printf '%b\n' "  - lint: Run golangci-lint"
	@printf '%b\n' "  - lint-fix: Run golangci-lint with auto-fix"
	@printf '%b\n' "  - qa: Run all quality checks (tests + lint)"
	@printf '%b\n' ""
	@printf '%b\n' "Test:"
	@printf '%b\n' "  - test t: Run unit tests"
	@printf '%b\n' "  - test.all: Run all tests (unit + integration)"
	@printf '%b\n' "  - test.integration: Run integration tests only"
	@printf '%b\n' "  - test.unit: Run unit tests (excludes integration tests)"

.PHONY: help-build
help-build: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: build"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  "
	@printf '%b\n' "  Builds the make-help binary."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:10"

.PHONY: help-clean
help-clean: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: clean"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  Deletes all built artifacts."
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:17"

.PHONY: help-lint
help-lint: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: lint"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  "
	@printf '%b\n' "  Run golangci-lint"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:49"

.PHONY: help-lint-fix
help-lint-fix: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: lint-fix"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  Run golangci-lint with auto-fix"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:54"

.PHONY: help-qa
help-qa: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: qa"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  Run all quality checks (tests + lint)"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:59"

.PHONY: help-test
help-test: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: test"
	@printf '%b\n' "Aliases: t"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  "
	@printf '%b\n' "  Run unit tests"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:31"

.PHONY: help-test.all
help-test.all: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: test.all"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  Run all tests (unit + integration)"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:43"

.PHONY: help-test.integration
help-test.integration: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: test.integration"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  Run integration tests only"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:38"

.PHONY: help-test.unit
help-test.unit: $(MAKE_HELP_DIR)help.mk
	@printf '%b\n' "Target: test.unit"
	@printf '%b\n' ""
	@printf '%b\n' "Documentation:"
	@printf '%b\n' "  "
	@printf '%b\n' "  Run unit tests (excludes integration tests)"
	@printf '%b\n' ""
	@printf '%b\n' "Source: /Users/zane/playground/sdlcforge/make-help/Makefile:24"

# Auto-regenerate help when source Makefiles change
$(MAKE_HELP_DIR)help.mk: $(MAKE_HELP_MAKEFILES)
	@make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 npx make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 echo "make-help not found; install with 'go install github.com/sdlcforge/make-help/cmd/make-help@latest' or 'npm install -g make-help'"
