# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --no-color

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MAKE_HELP_MAKEFILES := $(MAKE_HELP_DIR)Makefile

.PHONY: help
## Displays help for available targets.
help: $(MAKE_HELP_DIR)help.mk
	@echo "Usage: make [<target>...] [<ENV_VAR>=<value>...]"
	@echo ""
	@echo "Targets:"
	@echo ""
	@echo "Build:"
	@echo "  - #: Cross-compiles for multiple platforms."
	@echo "    Vars: PLATFORMS Target platforms (default: linux/amd64,darwin/amd64)"
	@echo "  - build: Categorized Project Example This example demonstrates using !category to organize targets into logical groups. Categories appear as section headers. Builds the production binary with optimizations."
	@echo "    Vars: LDFLAGS Linker flags for build"
	@echo "  - build-debug: Builds with debug symbols and race detector."
	@echo ""
	@echo "Development:"
	@echo "  - generate: Generates code (mocks, protobuf, etc)."
	@echo "  - serve run, dev: Runs the application locally."
	@echo "    Vars: PORT Server port (default: 8080), DEBUG Enable debug mode (default: false)"
	@echo "  - watch: Watches for changes and rebuilds."
	@echo ""
	@echo "Maintenance:"
	@echo "  - clean: Removes all build artifacts."
	@echo "  - deps: Updates dependencies."
	@echo "  - lint: Runs linters and formatters."
	@echo "    Vars: LINT_FLAGS Additional golangci-lint flags"
	@echo ""
	@echo "Test:"
	@echo "  - bench: Runs benchmarks."
	@echo "    Vars: BENCH_TIME Duration for each benchmark (default: 3s)"
	@echo "  - test: Runs the full test suite."
	@echo "    Vars: TEST_TIMEOUT Timeout for tests (default: 5m)"
	@echo "  - test-coverage: Runs tests with coverage report."

.PHONY: help-#
help-#: $(MAKE_HELP_DIR)help.mk
	@echo "Target: #"
	@echo "Variables:"
	@echo "  - PLATFORMS Target platforms (default: linux/amd64,darwin/amd64)"
	@echo ""
	@echo "Documentation:"
	@echo "  Cross-compiles for multiple platforms."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:23"

.PHONY: help-build
help-build: $(MAKE_HELP_DIR)help.mk
	@echo "Target: build"
	@echo "Variables:"
	@echo "  - LDFLAGS Linker flags for build"
	@echo ""
	@echo "Documentation:"
	@echo "  Categorized Project Example"
	@echo "  "
	@echo "  This example demonstrates using !category to organize targets"
	@echo "  into logical groups. Categories appear as section headers."
	@echo "  "
	@echo "  Builds the production binary with optimizations."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:13"

.PHONY: help-build-debug
help-build-debug: $(MAKE_HELP_DIR)help.mk
	@echo "Target: build-debug"
	@echo ""
	@echo "Documentation:"
	@echo "  Builds with debug symbols and race detector."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:18"

.PHONY: help-generate
help-generate: $(MAKE_HELP_DIR)help.mk
	@echo "Target: generate"
	@echo ""
	@echo "Documentation:"
	@echo "  Generates code (mocks, protobuf, etc)."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:59"

.PHONY: help-serve
help-serve: $(MAKE_HELP_DIR)help.mk
	@echo "Target: serve"
	@echo "Aliases: run, dev"
	@echo "Variables:"
	@echo "  - PORT Server port (default: 8080)"
	@echo "  - DEBUG Enable debug mode (default: false)"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs the application locally."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:49"

.PHONY: help-watch
help-watch: $(MAKE_HELP_DIR)help.mk
	@echo "Target: watch"
	@echo ""
	@echo "Documentation:"
	@echo "  Watches for changes and rebuilds."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:54"

.PHONY: help-clean
help-clean: $(MAKE_HELP_DIR)help.mk
	@echo "Target: clean"
	@echo ""
	@echo "Documentation:"
	@echo "  Removes all build artifacts."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:64"

.PHONY: help-deps
help-deps: $(MAKE_HELP_DIR)help.mk
	@echo "Target: deps"
	@echo ""
	@echo "Documentation:"
	@echo "  Updates dependencies."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:69"

.PHONY: help-lint
help-lint: $(MAKE_HELP_DIR)help.mk
	@echo "Target: lint"
	@echo "Variables:"
	@echo "  - LINT_FLAGS Additional golangci-lint flags"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs linters and formatters."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:75"

.PHONY: help-bench
help-bench: $(MAKE_HELP_DIR)help.mk
	@echo "Target: bench"
	@echo "Variables:"
	@echo "  - BENCH_TIME Duration for each benchmark (default: 3s)"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs benchmarks."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:41"

.PHONY: help-test
help-test: $(MAKE_HELP_DIR)help.mk
	@echo "Target: test"
	@echo "Variables:"
	@echo "  - TEST_TIMEOUT Timeout for tests (default: 5m)"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs the full test suite."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:30"

.PHONY: help-test-coverage
help-test-coverage: $(MAKE_HELP_DIR)help.mk
	@echo "Target: test-coverage"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs tests with coverage report."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/categorized-project/Makefile:35"

# Auto-regenerate help when source Makefiles change
$(MAKE_HELP_DIR)help.mk: $(MAKE_HELP_MAKEFILES)
	@make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 npx make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 echo "make-help not found; install with 'go install github.com/sdlcforge/make-help/cmd/make-help@latest' or 'npm install -g make-help'"
