# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --create-help-target

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
GOBIN ?= $(MAKE_HELP_DIR).bin
MAKE_HELP_BIN := $(GOBIN)/make-help
MAKE_HELP_OPTS := --makefile-path $(MAKE_HELP_DIR)Makefile
MAKE_HELP_CMD := $(MAKE_HELP_BIN) $(MAKE_HELP_OPTS)

$(MAKE_HELP_BIN):
	GOBIN=$(abspath $(GOBIN)) go install github.com/sdlcforge/make-help/cmd/make-help@latest

.PHONY: help
# Displays help summary.
help: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD)

.PHONY: help-generate
help-generate: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target generate

.PHONY: help-serve
help-serve: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target serve

.PHONY: help-watch
help-watch: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target watch

.PHONY: help-deps
help-deps: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target deps

.PHONY: help-lint
help-lint: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target lint

.PHONY: help-clean
help-clean: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target clean

.PHONY: help-build
help-build: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target build

.PHONY: help-build-debug
help-build-debug: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target build-debug

.PHONY: help-build-all
help-build-all: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target build-all

.PHONY: help-test
help-test: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target test

.PHONY: help-bench
help-bench: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target bench

.PHONY: help-test-coverage
help-test-coverage: $(MAKE_HELP_BIN)
	@$(MAKE_HELP_CMD) --target test-coverage
