# Generated by make-help. DO NOT EDIT.
# Regenerate with: make-help --no-color

MAKE_HELP_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
MAKE_HELP_MAKEFILES := $(MAKE_HELP_DIR)Makefile

.PHONY: help
## Displays help for available targets.
help: $(MAKE_HELP_DIR)help.mk
	@echo "Usage: make [<target>...] [<ENV_VAR>=<value>...]"
	@echo ""
	@echo "Targets:"
	@echo ""
	@echo "Build:"
	@echo "  - build: Compiles the project."
	@echo "  - test: Runs tests."
	@echo ""
	@echo "Deploy:"
	@echo "  - deploy: Deploys to production."
	@echo "    Vars: DEPLOY_ENV Target environment (staging, production)"

.PHONY: help-build
help-build: $(MAKE_HELP_DIR)help.mk
	@echo "Target: build"
	@echo ""
	@echo "Documentation:"
	@echo "  Compiles the project."
	@echo "  This is a documented target - always visible."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/filtering-demo/Makefile:15"

.PHONY: help-test
help-test: $(MAKE_HELP_DIR)help.mk
	@echo "Target: test"
	@echo ""
	@echo "Documentation:"
	@echo "  Runs tests."
	@echo "  Also documented - always visible."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/filtering-demo/Makefile:21"

.PHONY: help-deploy
help-deploy: $(MAKE_HELP_DIR)help.mk
	@echo "Target: deploy"
	@echo "Variables:"
	@echo "  - DEPLOY_ENV Target environment (staging, production)"
	@echo ""
	@echo "Documentation:"
	@echo "  Deploys to production."
	@echo "  Documented and categorized."
	@echo ""
	@echo "Source: /Users/zane/playground/sdlcforge/make-help/examples/filtering-demo/Makefile:28"

# Auto-regenerate help when source Makefiles change
$(MAKE_HELP_DIR)help.mk: $(MAKE_HELP_MAKEFILES)
	@make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 npx make-help --makefile-path $(MAKE_HELP_DIR)Makefile --no-color || \
	 echo "make-help not found; install with 'go install github.com/sdlcforge/make-help/cmd/make-help@latest' or 'npm install -g make-help'"
